### ISSUE TITLE
Fix paths when saving

### ISSUE THREAD

**Issue by csaftoiu** [LogicalInnovation/sloth#2]
If we start sloth from a directory, add images from a subdirectory, and save the .json in that same subdirectory, the images are saved with the paths *relative to the working directory*.

Attempting to load the saved JSON file again with Sloth, fails, because the relative paths aren't correct.

Fix the saving mechanism so the paths are saved relative to the directory the JSON is saved in.

**Comment by vc-souza** [comment]
Hey @csaftoiu, I can reproduce the issue, and I've fixed it for JSON.
Does it also happen with the other file formats? From the code it seems like it, but the issue was only reported for JSON, so I'm asking.

**Comment by csaftoiu** [comment]
I'm not sure; I didnt check it with the other formats. Can you see if it applies to the others as well? Was it a JSON specific fix you did or a general one?

**Comment by vc-souza** [comment]
Gotcha, the fix is pretty general:
```python
os.path.relpath(os.path.abspath(image_filename), os.path.dirname(fname))
```
using the directory of the file to be saved as a starting point, we ask for the relative path for each image.

I can apply this fix to the base class, and test each file format on my end.

**Comment by csaftoiu** [comment]
Resolved!
